name: pythonworkshopII
# Add more channels from the community
dependencies:
  - python=3.6
  # - anaconda=3.6 -> get everything!
  # - bokeh=0.9.2
  # - numpy=1.9.*
  # - nodejs=0.10.*
  # - flask
  - pip:
    - black